Models/Lifecycle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BusinessTrip.Models
{
    public class Lifecycle
    {
        // ID 
        public int Id { get; set; }
        // Дата открытия
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime Opened { get; set; }
        // Дата распределения
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime?  Rejected{ get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime? Checking { get; set; }
        // Дата закрытия
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime? Closed { get; set; }
    }
}

Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessTrip.Models;
using Microsoft.AspNetCore.Authorization;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using static BusinessTrip.Models.Application;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Rotativa.AspNetCore;
using BusinessTrip.ViewModels;

namespace BusinessTrip.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly BusinessTripContext _context;

        public ApplicationsController(BusinessTripContext context)
        {
            _context = context;
        }

        // Просмотр подробных сведений о заявке
        public ActionResult Details(int id)
        {
            Application application = _context.Application.Find(id);

            if (application != null)
            {

                return PartialView("_Details", application);
            }
            return View("Index");
        }

        public IActionResult ExportToPDF()
        {
            return new ViewAsPdf();
     
        }

        public IActionResult GenerateApp(int id)
        {
            Application request = _context.Application.Find(id);
          

            if (request != null)
            {



                //return PartialView("GenerateApp", request);
                return new ViewAsPdf("GenerateApp", request) {

                    PageSize = Rotativa.AspNetCore.Options.Size.A4
                };
            }
            return View("RequestList");
        }
        //заявки користувача
        [Authorize]
       
        public IActionResult Index()
        {
            // получаем текущего пользователя
            User user = _context.User.Where(m => m.Email == HttpContext.User.Identity.Name).FirstOrDefault();

            var requests = _context.Application.Where(r => r.UserId == user.Id) //получаем заявки для текущего пользователя
                                     
                                    .Include(r => r.Lifecycle)  // добавляем жизненный цикл заявок
                                    .Include(r => r.User)         // добавляем данные о пользователях
                                    .OrderByDescending(r => r.Lifecycle.Opened); // упорядочиваем по дате по убыванию   

            return View(requests.ToList());
        }
        // всі заявки
        [Authorize(Roles = "admin")]
       
        public IActionResult RequestList()
        {
            User user = _context.User.Where(m => m.Email == HttpContext.User.Identity.Name).FirstOrDefault();

            var requests = _context.Application

                                    .Include(r => r.Lifecycle)  // добавляем жизненный цикл заявок
                                    .Include(r => r.User)         // добавляем данные о пользователях
                                    .OrderByDescending(r => r.Lifecycle.Opened); // упорядочиваем по дате по убыванию   

            return View(requests.ToList());
        }
        //Видалення заявки користувачем
        
        public IActionResult Delete(int id)
        {
            Application request = _context.Application.Find(id);
            // получаем текущего пользователя
            User user = _context.User.Where(m => m.Email == HttpContext.User.Identity.Name).First();
            if (request != null && request.UserId == user.Id && request.Status!=2&&request.Status!=3)
            {
                Lifecycle lifecycle = _context.Lifecycle.Find(request.LifecycleId);
                _context.Lifecycle.Remove(lifecycle);
                _context.SaveChanges();
            }
            else if (request != null&&user.RoleId==1)
            {
                Lifecycle lifecycle = _context.Lifecycle.Find(request.LifecycleId);
                _context.Lifecycle.Remove(lifecycle);
                _context.SaveChanges();
                return RedirectToAction("RequestList");
            }
            return RedirectToAction("Index");
        }
        //Видалення заявки адміном
   

     
      

        // GET: Applications/Create
        [Authorize]
        public IActionResult Create()
        {
            User user = _context.User.Where(m => m.Email == HttpContext.User.Identity.Name).FirstOrDefault();
            if (user != null)
            {
                return View();
            }
            return NotFound();
            
        }
        public ActionResult Lifecycle(int id)
        {
            Lifecycle lifecycle = _context.Lifecycle.Where(m => m.Id == id).First();

            if (lifecycle != null)
            {
                return PartialView("_Lifecycle", lifecycle);
            }
            return View("Index");
        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Application request, 
            List<string> Transport, string OtherTransport, 
            List<string> Foundation, string OtherFoundation)
        {   // получаем текущего пользователя
            User user = _context.User.Where(m => m.Email == HttpContext.User.Identity.Name).FirstOrDefault();
            if (user == null)
            {
                return RedirectToAction("Logout", "Account");
            }
            if (ModelState.IsValid)
            {
                // указываем статус Открыта у заявки
                request.Status = (int)RequestStatus.Open;
                //получаем время открытия
                DateTime current = DateTime.Now;

                //Создаем запись о жизненном цикле заявки
                Lifecycle newLifecycle = new Lifecycle() { Opened = current };
                request.Lifecycle = newLifecycle;

                //Добавляем жизненный цикл заявки
                _context.Lifecycle.Add(newLifecycle);

                // указываем пользователя заявки
                request.UserId = user.Id;

                string temp;
                foreach(string f in Foundation)
                {
                    temp = f;
                    if (f == "Інше") temp = OtherFoundation;
                    if(!_context.Foundation.Select(n=>n.Trip_Foundation).Contains(temp))
                    {
                        _context.Foundation.Add(new Foundation { Trip_Foundation = temp });
                        _context.SaveChanges();
                    }
                    _context.App_Fundation.Add(new App_Fundation
                    {
                        ApplicationId = request.Id,
                        FundationId = _context.Foundation.FirstOrDefault(n => n.Trip_Foundation == temp).Id
                    });
                    _context.SaveChanges();
                }

                foreach(string t in Transport)
                {
                    temp = t;
                    if (t == "Інше") temp = OtherTransport;
                    if (!_context.Transport.Select(n => n.TransportType).Contains(temp))
                    {
                        _context.Transport.Add(new Transport { TransportType = temp });
                        _context.SaveChanges();
                    }
                    _context.App_Transport.Add(new App_Transport
                    {
                        ApplicationId = request.Id,
                        TransportId = _context.Transport.FirstOrDefault(n => n.TransportType == temp).Id
                    });
                    _context.SaveChanges();
                }

                request.App_fundation_Id = request.Id;

                request.App_transport_Id = request.Id;

                //Добавляем заявку
                _context.Application.Add(request);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(request);
        }

        // GET: Applications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.Application.FindAsync(id);
            EditApplicationViewModel model = new EditApplicationViewModel
            {
                userId = application.UserId,
                Id = application.Id,
                Email = application.Email,
                Fullname = application.Fullname,
                Main_place_of_work = application.Main_place_of_work,
                Position_in_combination = application.Position_in_combination,
                Type = application.Type,
                Purpose = application.Purpose,
                Saving_salary = application.Saving_salary,
                Trip_city = application.Trip_city,
                Institution = application.Institution,
                Start_date = application.Start_date,
                End_date = application.End_date,
                Itinerary = application.Itinerary,
                App_transport = _context.Transport.Where(
                    el => (from t in _context.App_Transport
                           where t.ApplicationId == application.Id
                           select t.TransportId).Contains(el.Id)).Select(t => t.TransportType).ToList(),
                App_fundation = _context.Foundation.Where(
                    el => (from f in _context.App_Fundation
                           where f.ApplicationId == application.Id
                           select f.FundationId).Contains(el.Id)).Select(f => f.Trip_Foundation).ToList(),
                InstitutionLocation = application.InstitutionLocation,
                Allfundations = new List<string> { "запрошення", "витяг з протоколу засідання Вченої Ради факультету", "рапорт проректора" },

Controllers/applicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinessTrip.Models;

namespace BusinessTrip.Controllers
{
    public class applicationsController : Controller
    {
        private businesstripContext db = new businesstripContext();

        // GET: applications
        public ActionResult Index()
        {
            var application = db.application.Include(a => a.app_fundation).Include(a => a.app_transport).Include(a => a.user);
            return View(application.ToList());
        }

        // GET: applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            application application = db.application.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: applications/Create
        public ActionResult Create()
        {
            ViewBag.app_fundation_Id = new SelectList(db.app_fundation, "id", "id");
            ViewBag.app_transport_Id = new SelectList(db.app_transport, "id", "id");
            ViewBag.user_Id = new SelectList(db.user, "id", "last_name");
            return View();
        }

        // POST: applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,user_Id,email,fullname,main_place_of_work,position_in_combination,type,purpose,saving_salary,trip_city,trip_country,institution,start_date,end_date,itinerary,app_transport_Id,payment,app_fundation_Id,institutionLocation")] application application)
        {
            if (ModelState.IsValid)
            {
                db.application.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.app_fundation_Id = new SelectList(db.app_fundation, "id", "id", application.app_fundation_Id);
            ViewBag.app_transport_Id = new SelectList(db.app_transport, "id", "id", application.app_transport_Id);
            ViewBag.user_Id = new SelectList(db.user, "id", "last_name", application.user_Id);
            return View(application);
        }

        // GET: applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            application application = db.application.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.app_fundation_Id = new SelectList(db.app_fundation, "id", "id", application.app_fundation_Id);
            ViewBag.app_transport_Id = new SelectList(db.app_transport, "id", "id", application.app_transport_Id);
            ViewBag.user_Id = new SelectList(db.user, "id", "last_name", application.user_Id);
            return View(application);
        }

        // POST: applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,user_Id,email,fullname,main_place_of_work,position_in_combination,type,purpose,saving_salary,trip_city,trip_country,institution,start_date,end_date,itinerary,app_transport_Id,payment,app_fundation_Id,institutionLocation")] application application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.app_fundation_Id = new SelectList(db.app_fundation, "id", "id", application.app_fundation_Id);
            ViewBag.app_transport_Id = new SelectList(db.app_transport, "id", "id", application.app_transport_Id);
            ViewBag.user_Id = new SelectList(db.user, "id", "last_name", application.user_Id);
            return View(application);
        }

        // GET: applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            application application = db.application.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            application application = db.application.Find(id);
            db.application.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Applications/ChangeStatus.cshtml
@using System.Security.Claims
@using System.Linq;
@{
    ViewData["Title"] = "Редагувати";
    if (((ClaimsIdentity)User.Identity).Claims
                    .Where(c => c.Type == ClaimTypes.Role)
                    .Select(c => c.Value).Where(r => r == "admin").Count() != 0) { Layout = "~/Views/Shared/_AdminLayout.cshtml"; }
    else { Layout = "~/Views/Shared/_Layout.cshtml"; }
}
@model IEnumerable<Application>
@using BusinessTrip.Models
@{
    ViewBag.Title = "Список заявок";
    int i = 0;
}

    <section>
        <h2>Змінити статус заявки</h2>
        <p>Всього заявок: @(Model.Count<Application>())</p>
        <table>

            @foreach (var item in Model)
            {
                i++;
                <tr>
                    <td><b>@i</b></td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Lifecycle.Opened)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.LastName)
                    </td>

                    @using (Html.BeginForm())
                    {
                        <td>
                            @Html.Hidden("requestId", item.Id)
                            @Html.Display(item.Fullname)
                            @if (item.Status == (int)Application.RequestStatus.Open)
                            {
                                @Html.DropDownList("status", new[] { new SelectListItem() { Text = "На перевірці", Value = "2" },
                                    new SelectListItem() { Text = "Закрита", Value = "3" },new SelectListItem() { Text = "Відхилено", Value = "4" }})
                            }
                            else if (item.Status == (int)Application.RequestStatus.Checking)
                            {
                                @Html.DropDownList("status", new[] { new SelectListItem() { Text = "Закрита", Value = "3" }, new SelectListItem() { Text = "Відхилено", Value = "4" } })
                            }
                            else if (item.Status == (int)Application.RequestStatus.Rejected)
                            {
                                @Html.DropDownList("status", new[] { new SelectListItem() { Text = "Закрита", Value = "3" }, new SelectListItem() { Text = "На перевірці", Value = "2" } })
                            }

                        </td>
                        <td>
                            <input type="submit" value="Змінити статус" class="btn"/>
                        </td>
                    }
                </tr>
            }
        </table>
        <br />
        <br />
        <br />
    </section>

Views/Applications/ChangeStatusUser.cshtml
@using System.Security.Claims
@using System.Linq;
@{
    ViewData["Title"] = "Редагувати";
    if (((ClaimsIdentity)User.Identity).Claims
                    .Where(c => c.Type == ClaimTypes.Role)
                    .Select(c => c.Value).Where(r => r == "admin").Count() != 0) { Layout = "~/Views/Shared/_AdminLayout.cshtml"; }
    else { Layout = "~/Views/Shared/_Layout.cshtml"; }
}
@model IEnumerable<Application>
@using BusinessTrip.Models
@{
    ViewBag.Title = "Список заявок";
    int i = 0;
}

<section>
    <h2>Відхилені заявки</h2>
    <p>Всього заявок: @(Model.Count<Application>())</p>
    
        @if (Model.Where(item => item.Status != (int)Application.RequestStatus.Rejected).Count() == 0)
        {
            <h3>У вас немає відхилених заявок</h3>
        }
        else
        {<table>

    
    @foreach (var item in Model.Where(item => item.Status != (int)Application.RequestStatus.Rejected))
    {
        i++;
        <tr>
            <td><b>@i</b></td>



            @using (Html.BeginForm())
            {
                <td>
                    @Html.Hidden("requestId", item.Id)

                    @if (item.Status == (int)Application.RequestStatus.Rejected)
                    {
                        @Html.DropDownList("status", new[] { new SelectListItem() { Text = "Відкрита", Value = "1" } })
                    <td>
                        <input type="submit" value="Змінити статуc заявки" />
                    </td>
                    }

                    </td>

            }
        </tr>
    }
</table>}
</section>

Views/Applications/GenerateApp.cshtml
@model BusinessTrip.Models.Application
@{
    Layout = null;
}
<style>
    .page pre, .page p {
        font-size: 30px;
        font-family: 'Times New Roman';
    }

    .right {
        margin-left: 1100px;
    }
</style>



<section class="page">
    <div class="right">
        <p>Ректору</p>
        <p>Львівського національного</p>
        <p>університету</p>
        <p>імені Івана Франка</p>
        <p>проф. Мельнику В. П. </p>
        <br />
        <p>@Html.DisplayFor(m => m.Main_place_of_work)</p>
        <p>@Html.DisplayFor(m => m.Position_in_combination) </p>
        <p>@Html.DisplayFor(m => m.Fullname)</p>
        </div>
    <div>
        <p align="center">Заява</p>
        <p style="margin-left:20px">
            Прошу вас відрядити мене @Html.DisplayFor(m => m.Saving_salary) y @Html.DisplayFor(m => m.Institution), @Html.DisplayFor(m => m.InstitutionLocation) з метою @Html.DisplayFor(m => m.Purpose) терміном на @Html.DisplayFor(m => (m.End_date - m.Start_date).Days) з @Html.DisplayFor(m => m.Start_date) по @Html.DisplayFor(m => m.End_date).
        </p>
        <br />
        <p>@Html.DisplayFor(m => m.Payment).</p>
        <br />
        <pre>Транспорт: @Html.DisplayFor(m=>m.App_transport_Id)</pre>
        <pre>Маршрут руху: @Html.DisplayFor(m=>m.Itinerary)</pre>
        <pre>Підстава: @Html.DisplayFor(m=>m.App_fundation_Id)</pre>
        <br />
        <br />
        <br />
        <pre>Дата                                                                                                                                        Підпис</pre><br/>
        <pre>ВК до наказу_______________________                   ______________________                __________________________</pre>
        <div>
        <pre style="margin-top:-10px"><sup><sup><sup>Підпис профільного проректора/ректора</sup></sup></sup>                                                    <sup><sup><sup>дата</sup></sup></sup>                                           <sup></sup><sup><sup>Розшифровка підпису</sup></sup></sup></pre>
        </div>
        </div>
</section>

Views/Applications/Index.cshtml
@model IEnumerable<Application>
@using BusinessTrip.Models

@{
    ViewBag.Title = "Список заявок";
    int i = 0; //счетчик
}
@using System.Security.Claims
@using System.Linq;
@{
    ViewData["Title"] = "Редагувати";
    if (((ClaimsIdentity)User.Identity).Claims
                    .Where(c => c.Type == ClaimTypes.Role)
                    .Select(c => c.Value).Where(r => r == "admin").Count() != 0) { Layout = "~/Views/Shared/_AdminLayout.cshtml"; }
    else { Layout = "~/Views/Shared/_Layout.cshtml"; }
}
<section>
    <h2>Список моїх заявок</h2>
    <p>Всього заявок: @(Model.Count<Application>())</p>
    <a class="btn" asp-action="ChangeStatusUser" asp-controller="Applications">Відхилені заявки</a>
    <table>

        @foreach (var item in Model)
        {
            i++;
            <tr>
                <td><b>@i</b></td>
                <td>
                    @if (item.Status == (int)Application.RequestStatus.Open)
                    {
                        <img src="~/Content/pictures/open (1).png" title="Заявка відкрита" class="tdImage" />
                    }

                    else if (item.Status == (int)Application.RequestStatus.Checking)
                    {
                        <img src="~/Content/pictures/view.png" title="Заявка на перевірці" class="tdImage" />
                    }
                    else if (item.Status == (int)Application.RequestStatus.Rejected)
                    {
                        <img src="~/Content//pictures/rejected.png" title="Заявку відхилено" class="tdImage" />
                    }
                    else if (item.Status == (int)Application.RequestStatus.Closed)
                    {
                        <img src="~/Content/pictures/closed.png" title="Заявку закрито" class="tdImage" />
                    }
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.Lifecycle.Opened)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fullname)
                </td>

                <td>

                    <div>
                        <a class="openDialog" data-dialog-id="infoDialog" data-dialog-title="Деталі заявки"
                           href="Applications/Details/@item.Id">
                            <img src="~/Content/pictures/details.png" class="tdImage" title="Деталі заявки" />
                        </a>
                    </div>
                </td>

                <td>
                    <div>
                        <a class="openDialog" data-dialog-id="lifecycleDialog" data-dialog-title="Життєвий цикл заявки"
                           href="Applications/Lifecycle/@item.LifecycleId">

                            <img src="~/Content/pictures/lifecycle.png" class="tdImage" title="Життєвий цикл заявки" />

                        </a>
                    </div>

                </td>

                <td>
                    <div>
                        <a asp-controller="Applications" asp-action="Edit" asp-route-id="@item.Id" data-dialog-title="Редагувати заявку">

                            <img src="~/Content/pictures/editApp.png" class="tdImage" title="Редагувати заявку" />

                        </a>
                    </div>
                </td>

                <td>
                    @*@Html.ActionLink("Згенерувати заяву", "GenerateApp", new { id = item.Id })*@
                    <a asp-action="GenerateApp" asp-route-id="@item.Id">
                        <img src="~/Content/pictures/generate.png" class="tdImage" title="Згенерувати заяву" />
                    </a>
                </td>


                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id">
                        <img src="~/Content/pictures/deleteApp.png" class="tdImage" title="Видалити заявку" />
                    </a>
                </td>
            </tr>

        }

    </table>
</section>

Views/Applications/RequestList.cshtml
@model IEnumerable<Application>
@using BusinessTrip.Models

@{
    ViewBag.Title = "Список заявок";
    int i = 0; //счетчик
}
@using System.Security.Claims
@using System.Linq;
@{
    ViewData["Title"] = "Редагувати";
    if (((ClaimsIdentity)User.Identity).Claims
                    .Where(c => c.Type == ClaimTypes.Role)
                    .Select(c => c.Value).Where(r => r == "admin").Count() != 0) { Layout = "~/Views/Shared/_AdminLayout.cshtml"; }
    else { Layout = "~/Views/Shared/_Layout.cshtml"; }
}
    <section>
        <h2>Список заявок користувачів</h2>
        <p>Всього заявок: @(Model.Count<Application>())</p>
        <a class="btn" asp-action="ChangeStatus" asp-controller="Applications">Змінити статус</a>
        <table>

            @foreach (var item in Model)
            {
                i++;
                <tr>
                    <td><b>@i</b></td>
                    <td>
                        @if (item.Status == (int)Application.RequestStatus.Open)
                        {
                            <img src="~/Content/pictures/open (1).png" title="Заявка відкрита" class="tdImage" />
                        }

                        else if (item.Status == (int)Application.RequestStatus.Checking)
                        {
                            <img src="~/Content/pictures/view.png" title="Заявка на перевірці" class="tdImage" />
                        }
                        else if (item.Status == (int)Application.RequestStatus.Closed)
                        {
                            <img src="~/Content/pictures/closed.png" title="Заявку закрито" class="tdImage" />
                        }
                        else if (item.Status == (int)Application.RequestStatus.Rejected)
                        {
                            <img src="~/Content/pictures/rejected.png" title="Заявку відхилено" class="tdImage" />
                        }
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.Lifecycle.Opened)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fullname)
                    </td>

                    <td>

                        <div>
                            <a class="openDialog" data-dialog-id="infoDialog" data-dialog-title="Деталі заявки"
                               href="Details/@item.Id">
                                <img src="~/Content/pictures/details.png" class="tdImage" title="Деталі заявки" />
                            </a>
                        </div>
                    </td>

                    <td>
                        <div>
                            <a class="openDialog" data-dialog-id="lifecycleDialog" data-dialog-title="Життєвий цикл заявки"
                               href="Lifecycle/@item.LifecycleId">

                                <img src="~/Content/pictures/lifecycle.png" class="tdImage" title="Життєвий цикл заявки" />

                            </a>
                        </div>

                    </td>


                    <td>
                        @*@Html.ActionLink("Видалити", "Delete", new { id = item.Id })*@
                        <a asp-action="Delete" asp-route-id="@item.Id">
                            <img src="~/Content/pictures/deleteApp.png" class="tdImage" title="Видалити заявку" />
                        </a>

                    </td>

                    <td>
                        <div>
                            <a asp-controller="Applications" asp-action="Edit" asp-route-id="@item.Id" data-dialog-title="Редагувати заявку">

                                <img src="~/Content/pictures/editApp.png" class="tdImage" title="Редагувати заявку" />

                            </a>
                        </div>
                    </td>

                    <td>
                        @*@Html.ActionLink("Згенерувати заяву", "GenerateApp", new { id = item.Id })*@
                        <a asp-action="GenerateApp" asp-route-id="@item.Id">
                            <img src="~/Content/pictures/generate.png" class="tdImage" title="Згенерувати заяву" />
                        </a>
                    </td>


                </tr>

            }

        </table>
        <br />
        <br />
        <br />
    </section>